group 'com.wizzardo'
version '0.1-SNAPSHOT'

ext {
    descriptionString = 'Small library for smooth transitions in jME'
}

apply plugin: 'java'
//apply from: 'gradle/sonatype.gradle'

java.sourceCompatibility = 1.8

repositories {
    mavenCentral()
}

dependencies {
    runtimeOnly "org.jmonkeyengine:jme3-core:3.2.2-stable"
    testImplementation group: 'junit', name: 'junit', version: '4.12'
}
